blank_issues_enabled: false
contact_links:
  - name: UI/UX Related Issue
    url: https://github.com/Iranman/DaCollector-WebUI/issues
    about: Create your issue here if has ANYTHING to do with the UI/UX.
  - name: DaCollector Docs Issue
    url: https://github.com/Iranman/DaCollector
    about: Create your issue here if its related to DaCollector Docs.
  - name: DaCollector Website Issue
    url: https://github.com/Iranman/DaCollector
    about: Create your issue here if its related to the DaCollector Website.