name: No Response

on:
  schedule:
    # Schedule to run at 00:50 every Monday
    - cron: '50 0 * * 1'
  workflow_dispatch:

jobs:
  noResponse:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: >
            This issue has been automatically marked as stale because there has been no
            response to our request for more information from the original author. With
            only the information that is currently in the issue, we don't have enough
            information to take action. Please reach out if you have or find the answers
            we need so that we can investigate further. You can also reach out to us on
            Discord: https://discord.gg/vpeHDsg
          close-issue-message: >
            This issue has been automatically closed because there has been no response
            to our request for more information from the original author. With only the
            information that is currently in the issue, we don't have enough information
            to take action. Please reach out if you have or find the answers we need so
            that we can investigate further. You can also reach out to us on Discord:
            https://discord.gg/vpeHDsg
          days-before-issue-stale: 30
          days-before-issue-close: 7
          stale-issue-label: 'More Information Required'
          only-labels: 'More Information Required'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
